"""Guild Wars 1 skill template codes: encode and decode.

Spec: https://wiki.guildwars.com/wiki/Skill_template_format (Base64, lowest-bit-first).
Template codes store CANONICAL skill ids. PvP-split skills have different in-game ids; map them with
data/template_id_map.json (pvp_id -> canonical id) before encoding. Decoding returns canonical ids.
"""
import json
import os

B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
PROFESSIONS = ["None", "Warrior", "Ranger", "Monk", "Necromancer", "Mesmer", "Elementalist",
               "Assassin", "Ritualist", "Paragon", "Dervish"]
ATTRIBUTES = {
    "Fast Casting": 0, "Illusion Magic": 1, "Domination Magic": 2, "Inspiration Magic": 3, "Blood Magic": 4,
    "Death Magic": 5, "Soul Reaping": 6, "Curses": 7, "Air Magic": 8, "Earth Magic": 9, "Fire Magic": 10,
    "Water Magic": 11, "Energy Storage": 12, "Healing Prayers": 13, "Smiting Prayers": 14,
    "Protection Prayers": 15, "Divine Favor": 16, "Strength": 17, "Axe Mastery": 18, "Hammer Mastery": 19,
    "Swordsmanship": 20, "Tactics": 21, "Beast Mastery": 22, "Expertise": 23, "Wilderness Survival": 24,
    "Marksmanship": 25, "Dagger Mastery": 29, "Deadly Arts": 30, "Shadow Arts": 31, "Communing": 32,
    "Restoration Magic": 33, "Channeling Magic": 34, "Critical Strikes": 35, "Spawning Power": 36,
    "Spear Mastery": 37, "Command": 38, "Motivation": 39, "Leadership": 40, "Scythe Mastery": 41,
    "Wind Prayers": 42, "Earth Prayers": 43, "Mysticism": 44,
}
ATTRIBUTE_NAMES = {v: k for k, v in ATTRIBUTES.items()}

_MAP_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "template_id_map.json")
try:
    PVP_TO_TEMPLATE = {int(k): v for k, v in json.load(open(_MAP_PATH))["pvp_to_template"].items()}
except FileNotFoundError:
    PVP_TO_TEMPLATE = {}


def _width(value, minimum):
    w = max(int(value).bit_length(), 1)
    return max(w, minimum)


def _put(bits, value, n):
    for i in range(n):
        bits.append((value >> i) & 1)


def encode(primary, secondary="None", attributes=None, skills=None):
    """primary/secondary: profession name or id. attributes: {name_or_id: rank}. skills: 8 ids (0 = empty)."""
    p = primary if isinstance(primary, int) else PROFESSIONS.index(primary)
    s = secondary if isinstance(secondary, int) else PROFESSIONS.index(secondary or "None")
    attrs = [((a if isinstance(a, int) else ATTRIBUTES[a]), int(r)) for a, r in (attributes or {}).items() if int(r) > 0]
    ids = [PVP_TO_TEMPLATE.get(int(x), int(x)) for x in (skills or [])] + [0] * 8
    ids = ids[:8]
    bits = []
    _put(bits, 14, 4)          # type: skill template
    _put(bits, 0, 4)           # version
    pw = _width(max(p, s), 4)
    if (pw - 4) % 2:
        pw += 1
    _put(bits, (pw - 4) // 2, 2)
    _put(bits, p, pw)
    _put(bits, s, pw)
    _put(bits, len(attrs), 4)
    aw = _width(max([a for a, _ in attrs] or [0]), 4)
    _put(bits, aw - 4, 4)
    for a, r in attrs:
        _put(bits, a, aw)
        _put(bits, r, 4)
    sw = _width(max(ids), 8)
    _put(bits, sw - 8, 4)
    for x in ids:
        _put(bits, x, sw)
    bits.append(0)
    while len(bits) % 6:
        bits.append(0)
    return "".join(B64[sum(bits[i + j] << j for j in range(6))] for i in range(0, len(bits), 6))


def decode(code):
    bits = []
    for ch in code.strip():
        v = B64.index(ch)
        bits.extend((v >> j) & 1 for j in range(6))
    pos = 0

    def take(n):
        nonlocal pos
        v = sum(bits[pos + i] << i for i in range(n))
        pos += n
        return v

    header = take(4)
    if header == 14:
        take(4)                 # version
    elif header != 0:
        raise ValueError("not a skill template")
    pw = take(2) * 2 + 4
    primary, secondary = take(pw), take(pw)
    n_attr = take(4)
    aw = take(4) + 4
    attributes = {}
    for _ in range(n_attr):
        a = take(aw)
        attributes[ATTRIBUTE_NAMES.get(a, a)] = take(4)
    sw = take(4) + 8
    skills = [take(sw) for _ in range(8)]
    return {"primary": PROFESSIONS[primary], "secondary": PROFESSIONS[secondary],
            "attributes": attributes, "skills": skills}


if __name__ == "__main__":
    # Reference codes generated by gvg.report's encoder (2026-10-08)
    cases = [
        (("Assassin", "Elementalist", {"Shadow Arts": 12, "Critical Strikes": 12}, [2862, 0, 0, 0, 0, 0, 0, 0]),
         "OwZi8xjsozAAAAAAAAAAAA"),
        (("Elementalist", "Monk", {"Air Magic": 12, "Energy Storage": 12, "Protection Prayers": 3}, [205, 1349, 0, 0, 0, 0, 0, 2]),
         "OgNDgMz/MNjiKAAAAAAAAABA"),
        (("Warrior", "None", {"Strength": 12, "Axe Mastery": 12, "Tactics": 3}, [338, 1403, 336, 3443, 349, 0, 2, 1]),
         "OQATEZJXnRqsXhKaluCAQAEAA"),
    ]
    for args, want in cases:
        got = encode(*args)
        print("OK " if got == want else "MISMATCH", got, want, decode(got))
